[package]
name = "so-sysinfo"
version = "0.1.1"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
human_bytes = "0.4.3"
indexmap = "2.3.0"
libmacchina = "7.3.0"
os_info = "3.8.2"
ratatui = "0.27.0"
so-logo-ascii-generator-core = { git = "ssh://git@github.com/solaaradotnet/so-logo-ascii-generator" }
sysinfo = "0.31.2"
tui-nodes = "0.5.0"
